# Generated by Django 5.1.7 on 2025-04-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_postattachment_alter_post_images_delete_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='attachments',
        ),
    ]
