# Generated by Django 5.1.7 on 2025-04-13 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_postme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostMe',
        ),
    ]
