# Generated by Django 5.1.7 on 2025-04-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_delete_postme'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostThis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
