# Generated by Django 5.1.7 on 2025-04-16 23:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_delete_postthis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachment',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
