# Generated by Django 5.1.7 on 2025-04-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_postattachment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
