# Generated by Django 5.1.7 on 2025-04-16 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_postme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostMe',
        ),
    ]
