# Generated by Django 5.1.7 on 2025-04-17 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_delete_postme'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
