# Generated by Django 5.1.7 on 2025-04-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_postme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostMe',
        ),
    ]
