# Generated by Django 5.1.7 on 2025-04-17 15:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_delete_postme'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosdtMe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
