# Generated by Django 5.1.7 on 2025-04-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_posdtme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PosdtMe',
        ),
    ]
