# Generated by Django 5.1.7 on 2025-04-17 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_postattachment_video_alter_postattachment_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostMe',
        ),
    ]
