# Generated by Django 5.1.7 on 2025-04-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_me'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Me',
        ),
    ]
