# Generated by Django 5.1.7 on 2025-04-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_projecttag_post_project_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trend',
            new_name='Hashtag',
        ),
    ]
