# Generated by Django 5.1.7 on 2025-05-05 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0031_rename_trend_hashtag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
