# Generated by Django 5.1.7 on 2025-03-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_friends_follow_delete_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
