# Generated by Django 5.1.7 on 2025-03-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
