# Generated by Django 5.1.7 on 2025-03-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_charlie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charlie',
        ),
    ]
