# Generated by Django 5.1.7 on 2025-04-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_delete_charlie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('hobbyist', 'Hobbyist'), ('professional', 'Professional'), ('student', 'Student'), ('studio', 'Studio'), ('other', 'Other')], default='hobbyist', max_length=20),
        ),
    ]
