# Generated by Django 5.1.7 on 2025-04-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('hobbyist', 'Hobbyist'), ('professional', 'Professional'), ('student', 'Student'), ('studio', 'Studio'), ('freelance', 'Freelance')], default='hobbyist', max_length=20),
        ),
    ]
