# Generated by Django 5.1.7 on 2025-04-16 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_type',
        ),
    ]
