# Generated by Django 5.1.7 on 2025-04-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('hobbyist', 'Hobbyist'), ('professional', 'Professional'), ('enthusiast', 'Enthusiast'), ('studio', 'Studio'), ('freelance', 'Freelance')], default='enthusiast', max_length=20),
        ),
    ]
